# Generated by Django 4.2.2 on 2023-08-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking',
            field=models.CharField(blank=True, choices=[('SHIPPED', 'shipped'), ('ON THE WAY', 'on the way'), ('DELIVERED', 'delivered')], max_length=20, null=True),
        ),
    ]
