# Generated by Django 4.2.3 on 2023-08-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_order_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='number_of_items',
            field=models.IntegerField(default=0),
        ),
    ]
