# Generated by Django 4.2.3 on 2023-08-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_cartitem_number_of_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='number_of_items',
        ),
        migrations.AddField(
            model_name='items',
            name='number_of_items',
            field=models.IntegerField(default=0),
        ),
    ]
