# Generated by Django 4.2.3 on 2023-08-07 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_remove_cartitem_number_of_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='number_of_items',
            new_name='inventory',
        ),
    ]
